In [8]:
import pandas as pd
import json

with open('data.json', 'r') as json_file:
    data = json.load(json_file)
for record in data:
    fields = record.get("fields", {})
    record.pop("fields", None)
    record.update(fields)
    record.pop("datasetid", None)

df = pd.DataFrame(data)
df.to_json('data_reorganized.json', orient='records')
df.head()

,recordid,record_timestamp,temperature_normale_lissee_degc,annee,annee_mois_jour,jour,temperature_realisee_lissee_temperature_normale_lissee_degc,mois,horodate,temperature_realisee_lissee_degc,pseudo_rayonnement
0,f5107c77d86857e915ea01563fb9236bcecd61dd,2023-09-12T10:10:00.210+02:00,20.7,2022,2022-07-22,22,2.6,07,2022-07-22T05:00:00+02:00,23.3,78.0
1,5888ca8a015a47cd13c529219a2aa3bb1fe44fda,2023-09-12T10:10:00.210+02:00,21.1,2022,2022-07-21,21,2.8,07,2022-07-22T00:00:00+02:00,23.9,93.0
2,50c8aa1e92f924e2d87425b5f1b37d13313e984c,2023-09-12T10:10:00.210+02:00,23.4,2022,2022-07-21,21,3.1,07,2022-07-21T17:00:00+02:00,26.5,85.0
3,79690e1985c9d5d007dde9f775885f2498f92ee8,2023-09-12T10:10:00.210+02:00,22.8,2022,2022-07-21,21,2.8,07,2022-07-21T14:00:00+02:00,25.6,66.0
4,ee67bfd1d159e08e251f298b2423fcc07052e874,2023-09-12T10:10:00.210+02:00,22.0,2022,2022-07-21,21,2.7,07,2022-07-21T12:30:00+02:00,24.7,63.0